name: foodie_driver
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.8
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^16.3.0
  flutter_facebook_auth: ^5.0.11
  geolocator: ^10.1.0


  shared_preferences: ^2.2.2
  image_picker: ^1.0.5
  progress_dialog_null_safe: ^1.0.7
  provider: ^6.1.1
  url_launcher: ^6.2.2
  intl: ^0.18.1
  cached_network_image: ^3.3.1
  uuid: ^3.0.7
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.1
  photo_view: ^0.14.0
  video_player: ^2.8.1
  http: ^0.13.1
  smooth_page_indicator: ^1.1.0
  intl_phone_number_input: ^0.7.4
  pin_code_fields: ^8.0.1
  easy_localization: ^3.0.2
  google_maps_flutter: ^2.5.0
  flutter_polyline_points: ^1.0.0
  cupertino_icons: ^1.0.6
  flutter_native_image: ^0.0.6+1
  flutter_sound: ^9.2.13
  the_apple_sign_in: ^1.1.1
  video_compress: ^3.1.2
  location: ^5.0.3
  audioplayers: ^5.1.0
  flutterflow_paginate_firestore: ^1.0.3+1
  flutter_widget_from_html: ^0.14.10+1
  razorpay_flutter: ^1.3.5
  # flutter_stripe: ^10.0.0
  mercadopago_sdk: ^1.3.0
  paytm_allinonesdk: ^1.2.2
  flutterwave_standard: ^1.0.7
  flutter_paypal_native: ^2.1.0
  mailer: ^6.0.1
  map_launcher: ^3.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  webview_flutter: ^4.4.2

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/ic_launcher-playstore.png'

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/fonts/
    - assets/flags/
    - assets/audio/

  fonts:
    - family: Poppinsb
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppinsl
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

    - family: Poppinsm
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Poppinsr
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Poppinssb
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf